
/*Register User*/
export const USER_REGISTER = 'USER_REGISTER';

/*Signin user */
export const USER_SIGNIN_REQUET = 'USER_SIGNIN_REQUET';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FALIURE = 'USER_SIGNIN_FALIURE';

/*Logout user */
export const USER_LOGOUT_REQUET = 'USER_LOGOUT_REQUET';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FALIURE = 'USER_LOGOUT_FALIURE';

/*Get Hero List*/
export const SET_HERO_LIST_REQUEST = 'SET_HERO_LIST_REQUEST';
export const SET_HERO_LIST_SUCCESS = 'SET_HERO_LIST_SUCCESS';
export const SET_HERO_LIST_FALIURE = 'SET_HERO_LIST_FALIURE';

/*Add Hero*/
export const ADD_HERO_REQUEST = 'ADD_HERO_REQUEST';
export const ADD_HERO_SUCCESS = 'ADD_HERO_SUCCESS';
export const ADD_HERO_FALIURE = 'ADD_HERO_FALIURE';

/*Update Hero Power*/
export const UPDATE_HERO_POWER_REQUEST = 'UPDATE_HERO_POWER_REQUEST';
export const UPDATE_HERO_POWER_SUCCESS = 'UPDATE_HERO_POWER_SUCCESS';
export const UPDATE_HERO_POWER_FALIURE = 'UPDATE_HERO_POWER_FALIURE';
